{% set name = "gistim" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gistim-{{ version }}.tar.gz
  sha256: 8c7253be9b98ca7f28fc7eeb47b6c2d9c66d562c6a1e2e69dc0c52ad54cf483f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - black
    - geopandas
    - matplotlib-base
    - lmfit >=1.0
    - netCDF4
    - numba >=0.50
    - numpy
    - python >=3.7
    - rasterio >=1.0
    - scipy >=1.5
    - timml
    - xarray >=0.15

test:
  imports:
    - gistim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/deltares/imod/qgis-tim
  summary: GIS utilities for Tim(ML) Analytic Element modeling
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://deltares.gitlab.io/imod/qgis-tim
  dev_url: https://gitlab.com/deltares/imod/qgis-tim

extra:
  recipe-maintainers:
    - Huite
    - visr
