{% set name = "gistim" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gistim-{{ version }}.tar.gz
  sha256: 9d704ebc2d80b2332b5e6a5d1814c6d8a01effe7afd6bacacd8137de547f737f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - pandas
    - python >=3.8
    - timml
    - ttim
    - xarray >=0.15

test:
  imports:
    - gistim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/deltares/imod/qgis-tim
  summary: GIS utilities for TimML and TTim Analytic Element modeling
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://deltares.gitlab.io/imod/qgis-tim
  dev_url: https://gitlab.com/deltares/imod/qgis-tim

extra:
  recipe-maintainers:
    - Huite
    - visr
    - JoerivanEngelen
