{% set name = "gistim" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gistim-{{ version }}.tar.gz
  sha256: 45fd248b34db9edd76d25378d5c1a234737176dc1ffb20ff23a4a1fac78f812c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - pandas
    - python >={{ python_min }}
    - timml ==6.3.0
    - ttim ==0.6.5
    - xarray >=0.15

test:
  imports:
    - gistim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/deltares/imod/qgis-tim
  summary: GIS utilities for TimML and TTim Analytic Element modeling
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://deltares.gitlab.io/imod/qgis-tim
  dev_url: https://gitlab.com/deltares/imod/qgis-tim

extra:
  recipe-maintainers:
    - Huite
    - visr
    - JoerivanEngelen
